version: '3'
services:
  mongo:
    image: temawito/mongo:3.2
    restart: unless-stopped
    ports:
        - 23456:23456
    expose: 
        - 23456        
    command: mongod --port 23456
  myapp:
    image: myapp
    command: dockerize
        -wait tcp://mongo:23456 -timeout 10s
        bash -c "npm start"        
    environment:
        APP_DB_HOST: db
        APP_DB_USER: john
        APP_DB_PASSWORD: mysecretpassword
    ports:
        - "3001:3001"
    expose: 
        - "3001"
    depends_on: 
        - mongo        
  angularfe:
    build: .    
    image: temawito/angularfe:0.0.1
    restart: unless-stopped
    ports:
      - 8081:80
    depends_on:
      - myapp  

